# Generated by Django 4.1.9 on 2023-06-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_avatar_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="/ensong/static/images/user-default.png", upload_to="avatars", verbose_name="User Avatar"
            ),
        ),
    ]
