# Generated by Django 4.1.9 on 2023-06-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatars/user-default.png", upload_to="avatars", verbose_name="User Avatar"
            ),
        ),
    ]
