# Generated by Django 4.1.9 on 2023-06-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.CharField(blank=True, max_length=800, verbose_name="About User"),
        ),
    ]
